glslangvalidator -V vkFFT_single_c2c.comp -o vkFFT_single_c2c.spv
glslangvalidator -V vkFFT_single_c2r.comp -o vkFFT_single_c2r.spv  
glslangvalidator -V vkFFT_single_r2c.comp -o vkFFT_single_r2c.spv  
glslangvalidator -V vkFFT_single_c2c_afterR2C.comp -o vkFFT_single_c2c_afterR2C.spv  
glslangvalidator -V vkFFT_single_c2c_beforeC2R.comp -o vkFFT_single_c2c_beforeC2R.spv  
glslangvalidator -V vkFFT_grouped_c2c.comp -o vkFFT_grouped_c2c.spv  
glslangvalidator -V vkFFT_transpose_inplace.comp -o vkFFT_transpose_inplace.spv  
glslangvalidator -V vkFFT_grouped_convolution_1x1.comp -o vkFFT_grouped_convolution_1x1.spv  
glslangvalidator -V vkFFT_single_convolution_1x1.comp -o vkFFT_single_convolution_1x1.spv  
glslangvalidator -V vkFFT_single_convolution_afterR2C_1x1.comp -o vkFFT_single_convolution_afterR2C_1x1.spv  
glslangvalidator -V vkFFT_grouped_convolution_symmetric_2x2.comp -o vkFFT_grouped_convolution_symmetric_2x2.spv  
glslangvalidator -V vkFFT_single_convolution_symmetric_2x2.comp -o vkFFT_single_convolution_symmetric_2x2.spv  
glslangvalidator -V vkFFT_single_convolution_afterR2C_symmetric_2x2.comp -o vkFFT_single_convolution_afterR2C_symmetric_2x2.spv  
glslangvalidator -V vkFFT_grouped_convolution_nonsymmetric_2x2.comp -o vkFFT_grouped_convolution_nonsymmetric_2x2.spv  
glslangvalidator -V vkFFT_single_convolution_nonsymmetric_2x2.comp -o vkFFT_single_convolution_nonsymmetric_2x2.spv  
glslangvalidator -V vkFFT_single_convolution_afterR2C_nonsymmetric_2x2.comp -o vkFFT_single_convolution_afterR2C_nonsymmetric_2x2.spv  
glslangvalidator -V vkFFT_grouped_convolution_symmetric_3x3.comp -o vkFFT_grouped_convolution_symmetric_3x3.spv  
glslangvalidator -V vkFFT_single_convolution_symmetric_3x3.comp -o vkFFT_single_convolution_symmetric_3x3.spv  
glslangvalidator -V vkFFT_single_convolution_afterR2C_symmetric_3x3.comp -o vkFFT_single_convolution_afterR2C_symmetric_3x3.spv  
glslangvalidator -V vkFFT_grouped_convolution_nonsymmetric_3x3.comp -o vkFFT_grouped_convolution_nonsymmetric_3x3.spv  
glslangvalidator -V vkFFT_single_convolution_nonsymmetric_3x3.comp -o vkFFT_single_convolution_nonsymmetric_3x3.spv  
glslangvalidator -V vkFFT_single_convolution_afterR2C_nonsymmetric_3x3.comp -o vkFFT_single_convolution_afterR2C_nonsymmetric_3x3.spv  
glslangvalidator -V 8192/vkFFT_single_c2r_8192.comp -o 8192/vkFFT_single_c2r_8192.spv  
glslangvalidator -V 8192/vkFFT_single_r2c_8192.comp -o 8192/vkFFT_single_r2c_8192.spv 
glslangvalidator -V 8192/vkFFT_single_c2c_8192.comp -o 8192/vkFFT_single_c2c_8192.spv  
glslangvalidator -V 8192/vkFFT_single_c2c_for_transposition_8192.comp -o 8192/vkFFT_single_c2c_for_transposition_8192.spv 
glslangvalidator -V 8192/vkFFT_single_c2c_afterR2C_for_transposition_8192.comp -o 8192/vkFFT_single_c2c_afterR2C_for_transposition_8192.spv 
glslangvalidator -V 8192/vkFFT_single_c2c_beforeC2R_for_transposition_8192.comp -o 8192/vkFFT_single_c2c_beforeC2R_for_transposition_8192.spv 